#pragma once
#include "unix_tool_server.h"
#include "session_supervisor_lease_store.h"
#include <locale>
#include <sstream>

// Fixed dimensions only. Epoch is generated by the runtime, never an Agent
// label. Invalid input is rejected instead of interpolated into log JSON.
inline std::string GatewayObservation(const UnixToolServerHealth& h,
    const std::string& epoch, std::uint64_t wallMs, std::uint64_t steadyMs,
    const SessionSupervisorLeaseCapacity* leaseCapacity = nullptr)
{
    if (epoch.empty() || epoch.size() > 128 ||
        epoch.find_first_not_of("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.:-") != std::string::npos)
        return std::string();
    std::ostringstream out;
    out.imbue(std::locale::classic());
    out << "{\"schema\":\"heptatrader.gateway-metrics.v1\",\"authorization_effect\":\"NONE\""
        << ",\"service_epoch\":\"" << epoch << "\",\"observed_at_ms\":" << wallMs
        << ",\"monotonic_ms\":" << steadyMs
        << ",\"pending_connections\":" << h.pendingConnections
        << ",\"active_requests\":" << h.activeRequests
        << ",\"ready_owners\":" << h.readyOwners
        << ",\"max_pending_connections\":" << h.maxPendingConnections
        << ",\"queue_backpressure_rejections\":" << h.queueBackpressureRejections
        << ",\"owner_backpressure_rejections\":" << h.ownerBackpressureRejections
        << ",\"deadline_rejections\":" << h.deadlineRejections
        << ",\"cancelled_requests\":" << h.cancelledRequests
        << ",\"responses_delivered\":" << h.responsesDelivered
        << ",\"response_write_failures\":" << h.responseWriteFailures
        << ",\"metrics_saturated\":" << (h.metricsSaturated ? "true" : "false")
        << ",\"results\":[";
    for (std::size_t i = 0; i < h.results.size(); ++i)
    { if (i) out << ','; out << h.results[i]; }
    out << "],\"queue_wait_latency\":";
    WriteOmsLatencyJson(out, h.queueWaitLatency);
    out << ",\"execution_latency\":";
    WriteOmsLatencyJson(out, h.executionLatency);
    out << ",\"response_write_latency\":";
    WriteOmsLatencyJson(out, h.responseWriteLatency);
    if (leaseCapacity != nullptr)
    {
        out << ",\"lease_store\":";
        WriteSessionSupervisorLeaseCapacityJson(out, *leaseCapacity);
    }
    out << '}';
    return out.str();
}
