# Type Name          ID GECOS                              Home
u hepta-agent         - "HeptaTrader Agent client"          /var/lib/hepta-agent
u hepta-gateway       - "HeptaTrader Tool Gateway"          /var/lib/hepta-tool-gateway
u hepta-exec          - "HeptaTrader Simulator execution"   /var/lib/hepta-execution
