# HeptaTrader interface profiles
# Fill credential fields once; launcher will auto-load by selected venue.

$IB = @{
  HEPTA_VENUE = 'IB'
  HEPTA_ALLOW_IB_ORDERS = '1'
  HEPTA_ALLOW_IB_LIVE = '0'
  HEPTA_IB_LIVE_KILL_SWITCH = '1'
  HEPTA_IB_MARKET_DATA_TYPE = '1'
  HEPTA_IB_MAX_ORDER_QTY = '50000'
  HEPTA_IB_MAX_DAILY_ORDERS = '50000'
  HEPTA_IB_TEST_ORDER_LOOP = '0'
  HEPTA_IB_SYMBOL = 'USD.CNH'
  HEPTA_IB_ASYNC_PLACE_BUDGET = '3'
  HEPTA_IB_MD_LOG_INTERVAL_MS = '2000'
  HEPTA_IB_STRATEGY = 'fx_trend'
  HEPTA_IB_FX_TREND_FAST = '3'
  HEPTA_IB_FX_TREND_SLOW = '8'
  HEPTA_IB_FX_TREND_SIGNAL_INTERVAL = '1'
  HEPTA_IB_FX_TREND_SIGNAL_INTERVAL_MS = '300'
  HEPTA_IB_FX_TREND_SIGNAL_BPS = '0.2'
  HEPTA_IB_FX_TREND_MAX_POSITION = '25000'
  HEPTA_IB_FX_TREND_STOP_LOSS_BPS = '20'
  HEPTA_IB_FX_TREND_COOLDOWN_SEC = '1'
  HEPTA_IB_FX_SCALPING_SLOPE_WINDOW = '3'
  HEPTA_IB_FX_SCALPING_SIGNAL_INTERVAL = '1'
  HEPTA_IB_FX_SCALPING_MAX_POSITION = '1'
  HEPTA_IB_FX_SCALPING_SPREAD_BPS = '999'
  HEPTA_IB_FX_SCALPING_MIN_VOL_BPS = '0'
  HEPTA_IB_FX_SCALPING_HOLD_TIMEOUT_SEC = '10'
  HEPTA_IB_FX_SCALPING_TP_BPS = '50'
  HEPTA_IB_FX_SCALPING_SL_BPS = '50'
  HEPTA_IB_FX_SCALPING_COOLDOWN_SEC = '1'
  HEPTA_IB_SCALP_QTY = '1'
  HEPTA_IB_RECON_ALLOW_EXTERNAL_BASELINE = '1'
  HEPTA_IB_RECON_EXTERNAL_MAX_ABS_DRIFT = '10000'
  HEPTA_IB_RECON_EXTERNAL_MAX_REL_BPS = '1000'
  HEPTA_IB_ACCOUNT_SUMMARY_REFRESH_SEC = '60'
  HEPTA_IB_RECONNECT_RETRY_SEC = '10'
  HEPTA_IB_RESUBSCRIBE_ON_RECONNECT = '1'
  HEPTA_IB_OBS_LOW_OVERHEAD = '1'
}

$CTP = @{
  HEPTA_VENUE = 'CTP'
  HEPTA_CTP_BROKER_ID = ''
  HEPTA_CTP_USER_ID = ''
  HEPTA_CTP_PASSWORD = ''
  HEPTA_CTP_MD_FRONT = ''
  HEPTA_CTP_TD_FRONT = ''
}

$XT = @{
  HEPTA_VENUE = 'XT'
  HEPTA_XT_ACCOUNT = ''
  HEPTA_XT_PATH = 'D:\国金证券QMT交易端'
}

$COMMON = @{
  HEPTA_VENUE_PROMPT = '1'
  HEPTA_GLOBAL_KILL_SWITCH = '0'
  HEPTA_FLATTEN_ONLY = '0'
}
