#!/usr/bin/env python3
"""Wire the generated catalog and fixed decimal core into active boundaries."""

from __future__ import annotations

import json
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github/workflows/gap-closure-m3.yml"
SELF = Path(__file__)


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    return text.replace(old, new)


def extend_catalog() -> None:
    path = ROOT / "schemas/tool-catalog-v1.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    fields = [
        ("SessionToken", "session_token"),
        ("ToolCallId", "tool_call_id"),
        ("ToolName", "tool_name"),
        ("Instrument", "instrument"),
        ("OrderId", "order_id"),
        ("Symbol", "symbol"),
        ("Currency", "currency"),
        ("SecType", "sec_type"),
        ("Exchange", "exchange"),
        ("Side", "side"),
        ("OrderType", "order_type"),
        ("Quantity", "quantity"),
        ("LimitPrice", "limit_price"),
        ("ReferencePrice", "reference_price"),
        ("ExpiresAtMs", "expires_at_ms"),
        ("WaitTimeoutMs", "timeout_ms"),
        ("AfterEventSequence", "after_sequence"),
        ("TimeInForce", "tif"),
        ("QueueDeadlineAtMs", "queue_deadline_at_ms"),
        ("CancelToolCallId", "cancel_tool_call_id"),
        ("TargetToolName", "target_tool_name"),
        ("ProtocolMinVersion", "protocol_min_version"),
        ("ProtocolMaxVersion", "protocol_max_version"),
        ("ExpectedSchemaHash", "expected_schema_hash"),
        ("PreviewPermit", "preview_permit"),
        ("TargetCommandId", "command_id"),
    ]
    value["fields"] = [
        {"id": index, "name": name, "symbol": symbol}
        for index, (symbol, name) in enumerate(fields, start=1)
    ]
    value["numeric_policy"] = {
        "id": "hepta.numeric.fixed-v1",
        "scale": 1_000_000,
        "maximum_raw": 9_000_000_000_000_000,
    }
    value["target_intent_aliases"] = {
        "max_slippage_bps": "reference_price",
        "target_position": "quantity",
    }
    value["target_intent_tools"] = [
        "intent.apply_target_position",
        "intent.preview_target_position",
    ]
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def patch_cpp_binding() -> None:
    path = ROOT / "HeptaTrade/tool_host/typed_tool_protocol.cpp"
    text = path.read_text(encoding="utf-8")
    text = replace_once(
        text,
        '#include "../tools/trading_tool_wire_contract.h"\n',
        '#include "../tools/trading_tool_wire_contract.h"\n'
        '#include "../numeric/fixed_decimal.h"\n',
        "numeric include",
    )
    pattern = re.compile(
        r"enum FieldId\n\{.*?\n\};\n\n"
        r"const char\* FieldName\(unsigned int id\)\n\{.*?\n\}\n",
        re.DOTALL,
    )
    marker = (
        "// HEPTA-GENERATED-WIRE-CATALOG-BEGIN\n"
        "// generated by scripts/generate_contract_bindings.py\n"
        "// HEPTA-GENERATED-WIRE-CATALOG-END\n"
    )
    text, count = pattern.subn(marker, text)
    if count != 1:
        raise SystemExit(f"C++ generated region: expected one match, found {count}")

    number_marker = "template <typename T>\nstd::string Number(T value)\n"
    number_overload = '''std::string Number(double value)
{
    HeptaFixedDecimal fixed;
    std::string reason;
    if (!HeptaFixedDecimal::FromDoubleExact(value, fixed, reason))
        return "invalid";
    return fixed.ToCanonicalString();
}

'''
    text = replace_once(
        text,
        number_marker,
        number_overload + number_marker,
        "fixed encoder overload",
    )

    parse_pattern = re.compile(
        r"bool ParseDouble\(const std::string& value, double& out\)\n"
        r"\{.*?\n\}\n\n"
        r"typedef std::map<unsigned int, std::string> DecodedFields;",
        re.DOTALL,
    )
    parse_replacement = '''bool ParseDouble(const std::string& value, double& out)
{
    if (!CanonicalFloating(value)) return false;
    HeptaFixedDecimal fixed;
    std::string reason;
    if (!HeptaFixedDecimal::ParseCanonical(value, fixed, reason))
        return false;
    out = fixed.ToDouble();
    return true;
}

typedef std::map<unsigned int, std::string> DecodedFields;'''
    text, count = parse_pattern.subn(parse_replacement, text)
    if count != 1:
        raise SystemExit(f"fixed decoder: expected one match, found {count}")
    path.write_text(text, encoding="utf-8")


def patch_python_binding() -> None:
    path = ROOT / "adapters/mcp/hepta_mcp_server.py"
    text = path.read_text(encoding="utf-8")
    text = replace_once(
        text,
        'PROTOCOL_NAME = "hepta.agent-tools"\nPROTOCOL_VERSION = 1\n',
        "# HEPTA-GENERATED-WIRE-CATALOG-BEGIN\n"
        "# generated by scripts/generate_contract_bindings.py\n"
        "# HEPTA-GENERATED-WIRE-CATALOG-END\n",
        "Python generated region",
    )
    field_pattern = re.compile(r"FIELD_IDS = \{\n.*?\n\}\n\n", re.DOTALL)
    text, count = field_pattern.subn("", text, count=1)
    if count != 1:
        raise SystemExit(f"Python FIELD_IDS: expected one match, found {count}")

    alias_pattern = re.compile(
        r"# The public Agent contract uses domain names.*?"
        r"TARGET_INTENT_TOOLS = frozenset\(\{\n.*?\n\}\)\n\n",
        re.DOTALL,
    )
    text, count = alias_pattern.subn("", text, count=1)
    if count != 1:
        raise SystemExit(f"Python aliases: expected one match, found {count}")

    marker = "\ndef scalar_text(value):\n"
    helper = '''
def _fixed_decimal_text(value):
    if not math.isfinite(value):
        raise ValueError("tool arguments must contain finite numbers")
    if value == 0.0 and math.copysign(1.0, value) < 0.0:
        raise ValueError("tool arguments must use canonical zero")
    scaled = value * NUMERIC_SCALE
    nearest = round(scaled)
    if abs(scaled - nearest) > 0.000001:
        raise ValueError(
            "tool numeric argument does not match fixed numeric policy"
        )
    if abs(nearest) > NUMERIC_MAXIMUM_RAW:
        raise ValueError("tool numeric argument exceeds fixed numeric range")
    negative = nearest < 0
    magnitude = abs(nearest)
    whole, fraction = divmod(magnitude, NUMERIC_SCALE)
    text = str(whole)
    if fraction:
        text += "." + str(fraction).rjust(6, "0").rstrip("0")
    return "-" + text if negative else text

'''
    text = replace_once(
        text,
        marker,
        "\n" + helper + "def scalar_text(value):\n",
        "Python fixed helper",
    )
    text = replace_once(
        text,
        "    if isinstance(value, float):\n"
        "        if not math.isfinite(value):\n"
        "            raise ValueError(\"tool arguments must contain finite numbers\")\n"
        "        if value == 0.0 and math.copysign(1.0, value) < 0.0:\n"
        "            raise ValueError(\"tool arguments must use canonical zero\")\n"
        "        return str(value)\n",
        "    if isinstance(value, float):\n"
        "        return _fixed_decimal_text(value)\n",
        "Python scalar fixed conversion",
    )
    path.write_text(text, encoding="utf-8")


def patch_cmake() -> None:
    path = ROOT / "HeptaTrade/CMakeLists.txt"
    text = path.read_text(encoding="utf-8")
    marker = (
        "add_library(hepta_portfolio_core STATIC\n"
        "    portfolio/portfolio_compiler.cpp)\n"
        "hepta_runtime_target(hepta_portfolio_core)\n"
    )
    replacement = marker + (
        "\nadd_library(hepta_numeric_core STATIC\n"
        "    numeric/fixed_decimal.cpp)\n"
        "hepta_runtime_target(hepta_numeric_core)\n"
    )
    text = replace_once(text, marker, replacement, "numeric target")
    text = replace_once(
        text,
        "hepta_runtime_target(hepta_tool_protocol)\n",
        "hepta_runtime_target(hepta_tool_protocol)\n"
        "target_link_libraries(hepta_tool_protocol PUBLIC hepta_numeric_core)\n",
        "protocol numeric dependency",
    )
    path.write_text(text, encoding="utf-8")

    path = ROOT / "tests/CMakeLists.txt"
    text = path.read_text(encoding="utf-8")
    marker = (
        "add_executable(hepta_portfolio_compiler_tests\n"
        "    portfolio_compiler_tests.cpp)\n"
        "target_link_libraries(hepta_portfolio_compiler_tests\n"
        "    hepta_portfolio_core)\n"
        "hepta_register_core_test(hepta_portfolio_compiler_tests)\n"
    )
    addition = marker + (
        "\nadd_executable(hepta_fixed_decimal_tests\n"
        "    fixed_decimal_tests.cpp)\n"
        "target_link_libraries(hepta_fixed_decimal_tests\n"
        "    hepta_numeric_core)\n"
        "hepta_register_core_test(hepta_fixed_decimal_tests)\n"
    )
    text = replace_once(text, marker, addition, "numeric test target")
    path.write_text(text, encoding="utf-8")


def patch_dev_loop() -> None:
    path = ROOT / "scripts/dev_core.sh"
    text = path.read_text(encoding="utf-8")
    marker = 'python3 "${ROOT_DIR}/scripts/generate_documentation_views.py" --check\n'
    text = replace_once(
        text,
        marker,
        'python3 "${ROOT_DIR}/scripts/generate_contract_bindings.py" --check\n'
        + marker,
        "contract generator gate",
    )
    path.write_text(text, encoding="utf-8")


def patch_schema_checker() -> None:
    path = ROOT / "scripts/check_schema_catalog.py"
    text = path.read_text(encoding="utf-8")
    marker = (
        "    if catalog.get(\"protocol_version\") != 1:\n"
        "        errors.append(\"tool catalog protocol version mismatch\")\n"
    )
    addition = marker + '''    numeric_policy = catalog.get("numeric_policy")
    if numeric_policy != {
        "id": "hepta.numeric.fixed-v1",
        "scale": 1_000_000,
        "maximum_raw": 9_000_000_000_000_000,
    }:
        errors.append("tool catalog numeric policy mismatch")
    fields = catalog.get("fields")
    if not isinstance(fields, list) or len(fields) != 26:
        errors.append("tool catalog field map is incomplete")
    else:
        actual_fields = {
            item.get("name"): item.get("id")
            for item in fields if isinstance(item, dict)
        }
        if actual_fields != CANONICAL_FIELD_IDS:
            errors.append("tool catalog field map drift")
        actual_symbols = {
            item.get("symbol"): (item.get("id"), item.get("name"))
            for item in fields if isinstance(item, dict)
        }
        if actual_symbols != CPP_FIELD_SYMBOLS:
            errors.append("tool catalog C++ field symbol drift")
    if catalog.get("target_intent_aliases") != TARGET_INTENT_TO_WIRE:
        errors.append("tool catalog target alias drift")
    if frozenset(catalog.get("target_intent_tools", [])) != TARGET_INTENT_TOOLS:
        errors.append("tool catalog target tool scope drift")
'''
    text = replace_once(text, marker, addition, "schema catalog generated fields")
    path.write_text(text, encoding="utf-8")


def patch_governance() -> None:
    path = ROOT / "docs/modules/source-ownership-registry-v1.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    value["physical_ownership_rules"].append({
        "id": "numeric-core",
        "selector": {"kind": "directory", "path": "HeptaTrade/numeric/"},
        "physical_owner": "hepta.numeric.core",
        "priority": 200,
    })
    path.write_text(
        json.dumps(value, ensure_ascii=False, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )

    path = ROOT / "docs/modules/manifests/hepta-numeric-core.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    value["lifecycle"] = "current"
    value["verification"] = ["numeric-negative", "numeric-properties"]
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    path = ROOT / "docs/modules/manifests/hepta-protocol-contracts.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    dependencies = value.setdefault("allowed_dependencies", [])
    if "hepta.numeric.core" not in dependencies:
        dependencies.append("hepta.numeric.core")
        dependencies.sort()
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    path = ROOT / "docs/verification/test-matrix-v2.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    for check in value["checks"]:
        if check["id"] == "numeric-properties":
            check["state"] = "implemented"
            check["evidence"] = (
                "fixed decimal core, overflow and cross-binding quantization tests"
            )
        elif check["id"] == "tool-catalog-drift":
            check["evidence"] = (
                "generated C++/Python/MCP binding parity and schema catalog checker"
            )
    path.write_text(
        json.dumps(value, ensure_ascii=False, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )

    path = ROOT / "docs/architecture/NUMERIC-POLICY.md"
    text = path.read_text(encoding="utf-8")
    old = (
        "## Migration\n\n"
        "当前 mixed-double 接缝标记为 G-NUM-001。迁移按 boundary type → adapter conversion → portfolio/risk → intent/permit → journal/event 顺序进行，并用 golden replay 证明经济和执行语义差异。\n"
    )
    new = (
        "## Implemented boundary\n\n"
        "`hepta.numeric.fixed-v1` 使用有符号 64 位 microunits（scale `1,000,000`），"
        "并把 raw 范围限制在 `±9,000,000,000,000,000`，使兼容 double 在规范化后仍保留"
        "单 microunit 整数身份。typed C++ wire 与 Python/MCP bridge 均从"
        "`schemas/tool-catalog-v1.json` 取得同一 numeric policy；编码输出 canonical decimal，"
        "解码拒绝 NaN、Inf、负零、范围溢出和超过六位小数的 scale mismatch。"
        "旧执行结构中的 double 仅是固定点验证后的兼容投影，不再是跨信任边界的权威表示。\n"
    )
    path.write_text(replace_once(text, old, new, "numeric status"), encoding="utf-8")


def main() -> None:
    extend_catalog()
    patch_cpp_binding()
    patch_python_binding()
    patch_cmake()
    patch_dev_loop()
    patch_schema_checker()
    patch_governance()
    subprocess.run(
        ["python3", "scripts/generate_contract_bindings.py", "--write"],
        cwd=ROOT,
        check=True,
    )
    subprocess.run(
        ["python3", "scripts/generate_documentation_views.py", "--write"],
        cwd=ROOT,
        check=True,
    )
    WORKFLOW.unlink()
    SELF.unlink()


if __name__ == "__main__":
    main()
