#!/usr/bin/env python3
"""Render field IDs and producer expressions from the maintained wire codecs.

Developer navigation only: this is not a C++ parser, compatibility checker or
new CI admission gate. Unsupported enum expressions fail rather than guessing.
The executable golden vectors exercise the real decoders independently.
"""
from __future__ import annotations
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
CODECS = (
    ("HSS1", "HeptaTrade/tool_host/session_supervisor_protocol.cpp"),
    ("HEX1 / version 11", "HeptaTrade/execution/execution_service_protocol.cpp"),
    ("HEV2 / version 2", "HeptaTrade/execution/execution_event_feed.cpp"),
)

def enum_fields(text: str) -> list[tuple[str, int]]:
    text = re.sub(r"//[^\n]*|/\*.*?\*/", "", text, flags=re.S)
    match = re.search(r"enum (?:FieldId|Field)(?:\s*:\s*unsigned int)?\s*\{([^}]+)\}", text)
    if not match:
        raise ValueError("wire field enum not found")
    result = []; current = -1
    for item in match.group(1).split(","):
        if not item.strip(): continue
        token = re.fullmatch(r"\s*(\w+)\s*(?:=\s*(\d+))?\s*", item)
        if not token: raise ValueError(f"unsupported enum expression: {item!r}")
        current = int(token[2]) if token[2] else current + 1
        result.append((token[1], current))
    if len({number for _, number in result}) != len(result):
        raise ValueError("duplicate field IDs")
    return result

def producer_expressions(text: str) -> dict[str, list[str]]:
    result = {}
    for match in re.finditer(r"AppendField\(\w+,\s*(\w+),\s*", text):
        i = match.end(); start = i; depth = 1; quoted = False; escaped = False
        while i < len(text) and depth:
            char = text[i]
            if quoted:
                if escaped: escaped = False
                elif char == "\\": escaped = True
                elif char == '"': quoted = False
            elif char == '"': quoted = True
            elif char == '(': depth += 1
            elif char == ')': depth -= 1
            i += 1
        if depth: raise ValueError("unterminated AppendField call")
        expression = re.sub(r"\s+", " ", text[start:i-1]).replace("|", "&#124;")
        values = result.setdefault(match[1], [])
        if expression not in values: values.append(expression)
    return result

TOOL_FIELDS = "HeptaTrade/tool_host/typed_tool_fields.def"
MCP_SOURCE = "adapters/mcp/hepta_mcp_server.py"
TOOL_BEGIN = "# generated-tool-fields:begin"
TOOL_END = "# generated-tool-fields:end"

def parse_tool_fields(text: str) -> list[tuple[str, int, str, bool]]:
    rows = []
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("//"):
            continue
        match = re.fullmatch(r'HEPTA_TOOL_FIELD\(([A-Za-z][A-Za-z0-9]*), ([0-9]+), "([a-z][a-z0-9_]*)", ([01])\)', line)
        if not match or not 1 <= int(match[2]) <= 255:
            raise ValueError("invalid canonical tool field")
        rows.append((match[1], int(match[2]), match[3], match[4] == "1"))
    if not rows or any(len({row[column] for row in rows}) != len(rows) for column in (0, 1, 2)):
        raise ValueError("empty or duplicate canonical tool fields")
    return rows

def mcp_field_block(rows: list[tuple[str, int, str, bool]]) -> str:
    return "\n".join([TOOL_BEGIN, "FIELD_IDS = {"] +
        [f'    "{name}": {number},' for _, number, name, supported in rows if supported] +
        ["}", TOOL_END])

def sync_tool_fields(root: Path, write: bool = False) -> None:
    rows = parse_tool_fields((root / TOOL_FIELDS).read_text(encoding="utf-8"))
    path = root / MCP_SOURCE
    text = path.read_text(encoding="utf-8")
    if text.count(TOOL_BEGIN) != 1 or text.count(TOOL_END) != 1:
        raise ValueError("MCP generated field markers missing or duplicated")
    begin, end = text.index(TOOL_BEGIN), text.index(TOOL_END) + len(TOOL_END)
    if end <= begin:
        raise ValueError("MCP generated field markers reversed")
    expected = mcp_field_block(rows)
    if text[begin:end] != expected:
        if not write:
            raise ValueError("MCP tag drift: run render_protocol_reference.py --write-tool-fields")
        path.write_text(text[:begin] + expected + text[end:], encoding="utf-8")

def render(root: Path = ROOT) -> str:
    out = ["# Wire field reference", "", "Status: CURRENT", "Applies to: current HTT1, HSS1, HEX1 and HEV2 codecs", "",
           "Generated by `python3 scripts/render_protocol_reference.py`. Numeric tags and producer expressions are extracted from the current codec; an unused enum entry is NOT an accepted request field. See [operation contracts](wire-operation-contracts.md) for exact field sets, units, bounds and recovery actions.", "",
           "All TLV values below are byte strings. `Number`/`to_string` emit decimal text; conditional `1`/`0` expressions encode booleans. Empty text is still a present field unless the operation forbids it. Numeric payloads are not native integer memory representations.", ""]
    for title, path in CODECS:
        source = (root/path).read_text(encoding="utf-8-sig")
        expressions = producer_expressions(source)
        out += [f"## {title}", "", f"Source: `{path}`", "", "| Tag | Field | Producer value / binding |", "|---:|---|---|"]
        for name, number in enum_fields(source):
            values = expressions.get(name)
            value = "; ".join(f"`{v}`" for v in values) if values else "Reserved/unused by current encoder; not an admission grant."
            out.append(f"| {number} | `{name}` | {value} |")
        out.append("")
    rows = parse_tool_fields((root / TOOL_FIELDS).read_text(encoding="utf-8"))
    out += ["## HTT1 / Agent tool request fields", "", f"Source: `{TOOL_FIELDS}`", "",
            "Tags and names are shared mechanically. Python profile exclusions remain explicit; this table does not grant field admission.", "",
            "| Tag | Field | Python MCP profile |", "|---:|---|---|"]
    out += [f"| {number} | `{name}` | {'Included' if supported else 'Excluded'} |" for _, number, name, supported in rows]
    out.append("")
    return "\n".join(out)

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--write-tool-fields", action="store_true")
    parser.add_argument("--check-tool-fields", action="store_true")
    args = parser.parse_args()
    if args.write_tool_fields or args.check_tool_fields:
        sync_tool_fields(args.root, write=args.write_tool_fields)
    else:
        print(render(args.root), end="")
    return 0

if __name__ == "__main__": raise SystemExit(main())
